### ISSUE TITLE
如果是调用本地摄像头可以吗？

### ISSUE THREAD

**Issue by llllllllu** [15225845996/face-test#1]
不添加外设，调用本地PC摄像头可以吗？期待您的回复，非常感谢

**Comment by 15225845996** [comment]
可以使用本地摄像头，用pc自带的摄像头集成会更方便，也更流畅------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;llllllllu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月2日(星期四) 凌晨0:00
收件人:&nbsp;&quot;15225845996/face-test&quot;<face-test@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[15225845996/face-test] 如果是调用本地摄像头可以吗？ (#1)

**Comment by llllllllu** [comment]
非常感谢您百忙之中的回复，搞了好几天本地摄像头启动，但是都失败了，如果您有也有实现这块代码，期待您尽快实现，指导下。因为之前没搞过java，无头苍蝇一样乱找，有点混乱，哈哈，再次感谢您，谢谢您

**Comment by 15225845996** [comment]
如果是使用浏览器直接调用pc的摄像头 播放 并人脸识别&nbsp; 可以再看一下&nbsp;https://github.com/15225845996/face-test&nbsp; ，我刚提交了一个调用本地的html和js&nbsp; &nbsp;项目启动后访问：http://localhost/local.html

如果要使用后台调用pc本地摄像头，可以使用opencv或其他的第三方jar包




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"llllllllu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 凌晨0:31
收件人:&nbsp;"15225845996/face-test"<face-test@noreply.github.com&gt;;
抄送:&nbsp;"山"<2664047294@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [15225845996/face-test] 如果是调用本地摄像头可以吗？ (#1)





 
非常感谢您百忙之中的回复，搞了好几天本地摄像头启动，但是都失败了，如果您有也有实现这块代码，期待您尽快实现，指导下。因为之前没搞过java，无头苍蝇一样乱找，有点混乱，哈哈，再次感谢您，谢谢您
